name: Lintcheck C++

on:
  push:
    branches:
      - main
    paths:
      - "src/main.cpp"
  pull_request:
    paths:
      - "src/main.cpp"

jobs:
  check_cpp:
    name: "clang-format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.14
      with:
        source: 'src/main.cpp'
        clangFormatVersion: 14
