name: Lint Python

on:
  push:
    branches:
      - main
    paths:
      - "src/main.cpp"
      - "nle_language_wrapper/**.py"
  pull_request:
    paths:
      - "src/main.cpp"
      - "nle_language_wrapper/**.py"

jobs:
  check_python:
    name: "Lint Python"

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python 3.9 env
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Upgrade pip if necessary
      run: "pip install -q --upgrade pip"
    - name: Install package
      run: "pip install -e .['dev']"
    - name: Run tests
      run: "make test"
    - name: Upload code coverage
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov